// Solo para demo/pruebas; no se importa desde las páginas de producción.
import type { DatosMH } from "./modelo"
export const ejemploMH = (): DatosMH => ({
  lotes: [
    {
      id: "m3",
      folio: "MAG-003 · ejemplo",
      material: "maguey",
      inicial: 2000,
      saldo: 2000,
      contexto: "Tobalá · Loma del Toro · Magueyes Don Pedro",
      nota: "",
      cuando: "2026-09-28T07:30:00",
      quien: "Aurelia",
    },
    {
      id: "m2",
      folio: "MAG-002 · ejemplo",
      material: "maguey",
      inicial: 4500,
      saldo: 1300,
      contexto: "Espadín · Loma del Toro",
      nota: "maduro, sin daño",
      cuando: "2026-09-25T07:30:00",
      quien: "Aurelia",
    },
    {
      id: "m1",
      folio: "MAG-001 · ejemplo",
      material: "maguey",
      inicial: 8000,
      saldo: 0,
      contexto: "Espadín · Loma del Toro",
      nota: "",
      cuando: "2026-09-02T07:30:00",
      quien: "Aurelia",
    },
    {
      id: "c2",
      folio: "AC-002 · ejemplo",
      material: "agave_cocido",
      inicial: 4900,
      saldo: 4900,
      contexto: "de HOR-002",
      nota: "leña de encino",
      cuando: "2026-09-28T08:00:00",
      quien: "Aurelia",
    },
  ],
  horneadas: [
    {
      id: "h3",
      folio: "HOR-003 · ejemplo",
      hornoId: "horno1",
      horno: "Horno 1",
      estado: "abierta",
      inicio: "2026-09-28T09:00:00",
      fin: null,
      cargados: 5200,
      cocidos: null,
      combustible: "",
      origenes: "MAG-004 · 3,200 kg / MAG-005 · 2,000 kg",
      quien: "Aurelia",
    },
    {
      id: "h1",
      folio: "HOR-001 · ejemplo",
      hornoId: "horno1",
      horno: "Horno 1",
      estado: "cerrada",
      inicio: "2026-09-02T09:00:00",
      fin: "2026-09-06T12:00:00",
      cargados: 8000,
      cocidos: 6200,
      combustible: "leña",
      origenes: "MAG-001 · 8,000 kg",
      quien: "Aurelia",
    },
  ],
  hornos: [{ id: "horno1", nombre: "Horno 1", capacidad: 10000 }],
  especies: [
    { id: "e1", nombre: "Tobalá" },
    { id: "e2", nombre: "Espadín" },
  ],
  predios: [{ id: "p1", nombre: "Loma del Toro" }],
  proveedores: [{ id: "s1", nombre: "Magueyes Don Pedro" }],
})
