// Runtime QA harness for the Design Hub. Serves the Hub statically and runs
// the four mandatory viewports. Generated by init-project.sh; edit freely.
import { defineConfig, devices } from '@playwright/test';

const PORT = process.env.HUB_QA_PORT || '4321';
const BASE_URL = `http://localhost:${PORT}`;

export default defineConfig({
  testDir: './tests',
  timeout: 30000,
  fullyParallel: false,
  reporter: [['list'], ['html', { open: 'never' }]],
  webServer: {
    command: `python3 -m http.server ${PORT} --directory ..`,
    url: BASE_URL,
    reuseExistingServer: true,
    timeout: 20000,
  },
  use: { baseURL: BASE_URL, screenshot: 'only-on-failure', trace: 'retain-on-failure' },
  projects: [
    { name: 'desktop-1440', use: { ...devices['Desktop Chrome'], viewport: { width: 1440, height: 900 } } },
    { name: 'desktop-1024', use: { ...devices['Desktop Chrome'], viewport: { width: 1024, height: 800 } } },
    { name: 'tablet-768',   use: { ...devices['Desktop Chrome'], viewport: { width: 768,  height: 900 } } },
    { name: 'mobile-390',   use: { ...devices['Desktop Chrome'], viewport: { width: 390,  height: 780 }, hasTouch: true, isMobile: true } },
  ],
});
